### ISSUE TITLE
bzz-link: add ens subdomain support

### ISSUE THREAD

**Issue by darkobas2** [ethersphere/gateway-proxy#306]
Feature request:

ens supports subdomains and bee seems to resolve them as well, but gateway-proxy always takes just the first "domain" in equation
https://github.com/ethersphere/gateway-proxy/blob/master/src/bzz-link.ts#L84

as a side note I would like to say that HOSTNAME env paramater is not well documented. I did not know I need it to get bzz.link functionality working

**Comment by agazso** [comment]
Unfortunately with bzz.link subdomains it is not possible to support ENS subdomains in general, because of the limitations of the multi-level SSL wildcard subdomains. You can read more about here:
https://stackoverflow.com/questions/2115611/wildcard-ssl-on-sub-subdomain#9743652

It is possible to support subdomains of a specific `.eth` domain up to one level, so if your ENS name is at `example.eth` and your DNS is `website.org`, then you can serve ENS subdomains with an `*.example.website.org` SSL certificate and using `example.website.org` as your hostname. Then the logic of using the first subdomain from the left still holds.

**Comment by darkobas2** [comment]
@agazso well certificates are irrelevant for the issue... different department :)

your suggestion unfortunately does not work.... 
sub.domain.example.com and if host in this case is domain.example.com gw-proxy will try find sub.eth which doesnt exist

also tried it and i get 404, while host[0] + '.' + host[1] works

**Comment by agazso** [comment]
Not sure why you think certificates are irrelevant. The whole point of the bzz.link subdomain service is to provide HTTP access to the swarm network. However the world is moving towards HTTPS by default, all the browsers are enforcing, therefore you cannot avoid the question of certificates practically.

The only exception where you can possibly use HTTP and not HTTPS is when using localhost and if you want to use that you don't even need the bzz.link/gateway-proxy because Bee supports localhost subdomains (even multiple levels) directly (well, it works in Chrome & Firefox, not in Safari, but again this is out of control for swarm).

**Comment by agazso** [comment]
> your suggestion unfortunately does not work.... sub.domain.example.com and if host in this case is domain.example.com gw-proxy will try find sub.eth which doesnt exist
> 
> also tried it and i get 404, while host[0] + '.' + host[1] works

So yes, ultimately maybe this does not work, PRs are welcome!

**Comment by darkobas2** [comment]
@agazso I know all of that, my usecase is hosting web site on swarm. benefit for me doing this with gateway-proxy way is you can host websites which are designed for "/" home without any modifications while going through bee /bzz would be added.

i will see what I can do regarding a PR :)

**Comment by darkobas2** [comment]
https://github.com/ethersphere/gateway-proxy/pull/308
